$axure.loadCurrentPage({
  "url":"manage1.html",
  "generationDate":new Date(1444806061037.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6b911ea4dc50413b81635f87cab5e4dd",
    "type":"Axure:Page",
    "name":"manage1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8fabb4a87e954c29a3457aaaa485f6a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":143},
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"351b49985a2d48e68d94b11cf9ca070b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":287,
                  "y":143},
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"c5bac97aee4a4491beecd5709acad012",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":307,
              "y":160},
            "size":{
              "width":340,
              "height":610}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc3e9a7f01184013b86a67f089f507d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":307,
                  "y":160},
                "size":{
                  "width":340,
                  "height":610}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/logined/u2.png"}},
{
          "id":"c3950ede12bc43998e496a0b3ee3a0b4",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":779},
            "size":{
              "width":375,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4715f3225ada42168b6e94b6ad36d51f",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"75b84c44e6714c9cab3ed5a47eb7e395",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5471901520404f5fac35214d4a6bd204",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":125,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open manage1 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"manage1.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u4.png"}},
{
                  "id":"2c7bd04157224d8c901d1f9f8f1042e7",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":125,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cca96b0af1904e1e832aab6de2aa0565",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":125,
                          "y":0},
                        "size":{
                          "width":125,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open manage2 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"manage2.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u4.png"}},
{
                  "id":"d6bab04b67cc4bf4909f203022eddf48",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":250,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ceafec9ac8f540b0a60fa684bc66818e",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":250,
                          "y":0},
                        "size":{
                          "width":125,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open setting in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"setting.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u8.png"}}]}]},
{
          "id":"59522fad905d45ff9bec5f916478c085",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":338,
              "y":194},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39a75766a9b54055ae258ccff6dc0cdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":338,
                  "y":194},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3108ef012905447196a228554214a579",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":438,
              "y":194},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf3a28ea767a4f65bd6e13e7b040017b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":438,
                  "y":194},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89561a24561445a78e3458bdb319cd65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":338,
              "y":254},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6338635fe303423394fdc2df426752a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":338,
                  "y":254},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52d3694f20a249f3ac8801391cad41ff",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":249.5},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d1a790239c174237b520fd712e0a236f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":338,
              "y":289},
            "size":{
              "width":58,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c7ad2dbfdcb4421acb9b553e0c132e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":338,
                  "y":289},
                "size":{
                  "width":58,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65f7ccec063a448ea71ee46f21b56f93",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":285},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"606f39b83ee94519a8201786d16dd780",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":330},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bd91662db0984889bc3f117741d8ac9b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":338,
              "y":330},
            "size":{
              "width":58,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b026f7841dbf426b9e5e75f82e45d04b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":445},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "8fabb4a87e954c29a3457aaaa485f6a7":{
      "scriptId":"u0"},
    "351b49985a2d48e68d94b11cf9ca070b":{
      "scriptId":"u1"},
    "c5bac97aee4a4491beecd5709acad012":{
      "scriptId":"u2"},
    "cc3e9a7f01184013b86a67f089f507d3":{
      "scriptId":"u3"},
    "c3950ede12bc43998e496a0b3ee3a0b4":{
      "scriptId":"u4"},
    "4715f3225ada42168b6e94b6ad36d51f":{
      "scriptId":"u5"},
    "75b84c44e6714c9cab3ed5a47eb7e395":{
      "scriptId":"u6"},
    "5471901520404f5fac35214d4a6bd204":{
      "scriptId":"u7"},
    "2c7bd04157224d8c901d1f9f8f1042e7":{
      "scriptId":"u8"},
    "cca96b0af1904e1e832aab6de2aa0565":{
      "scriptId":"u9"},
    "d6bab04b67cc4bf4909f203022eddf48":{
      "scriptId":"u10"},
    "ceafec9ac8f540b0a60fa684bc66818e":{
      "scriptId":"u11"},
    "59522fad905d45ff9bec5f916478c085":{
      "scriptId":"u12"},
    "39a75766a9b54055ae258ccff6dc0cdb":{
      "scriptId":"u13"},
    "3108ef012905447196a228554214a579":{
      "scriptId":"u14"},
    "cf3a28ea767a4f65bd6e13e7b040017b":{
      "scriptId":"u15"},
    "89561a24561445a78e3458bdb319cd65":{
      "scriptId":"u16"},
    "6338635fe303423394fdc2df426752a0":{
      "scriptId":"u17"},
    "52d3694f20a249f3ac8801391cad41ff":{
      "scriptId":"u18"},
    "d1a790239c174237b520fd712e0a236f":{
      "scriptId":"u19"},
    "6c7ad2dbfdcb4421acb9b553e0c132e9":{
      "scriptId":"u20"},
    "65f7ccec063a448ea71ee46f21b56f93":{
      "scriptId":"u21"},
    "606f39b83ee94519a8201786d16dd780":{
      "scriptId":"u22"},
    "bd91662db0984889bc3f117741d8ac9b":{
      "scriptId":"u23"},
    "b026f7841dbf426b9e5e75f82e45d04b":{
      "scriptId":"u24"}}});