$axure.loadCurrentPage({
  "url":"login.html",
  "generationDate":new Date(1444806059989.84),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f4568c6cfdb349779f99a5b750b12504",
    "type":"Axure:Page",
    "name":"login",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d0514a3d76674fc2abc45894aa522019",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":27},
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad02e4e277724cf5a5dd96bc7aed422b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":27},
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"01d8a89949864262af329337b1b05a65",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":245},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3ac1b31e714e41688e7b28a3a29d8183",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":305},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"49746ca9e13f48e8a173c2051a01522f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":245},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4092257f08843caac08804c007121e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":245},
                "size":{
                  "width":60,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"268790c6c5534d1f9965b945a5983b58",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":305},
            "size":{
              "width":55,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07cb06d9d2be4e7490b42df68779b11b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":305},
                "size":{
                  "width":55,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c0162fe40c949e9a98ace9656e08eec",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":343,
              "y":425},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open logined in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"logined.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"ef1d9b194d8748edb22d224a26aa5af8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":50},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"2f881690fd15417983375c0d3b170beb",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":212,
              "y":664},
            "size":{
              "width":375,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cfa170e8ef0498f8691ed28fb42c0c2",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2ab043dd0e9541be9c3fed467e4f817d",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"133e382b03ac40e3a192438541fb8e97",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":125,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Home in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"home.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u4.png"}},
{
                  "id":"a2f973229a2c4bc7a22ec8f7f36d9eb7",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":125,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7f78bcaf1f9b4e2b820225cb61d9243d",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":125,
                          "y":0},
                        "size":{
                          "width":125,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open login in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"login.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u4.png"}},
{
                  "id":"f49a1a804c204a3484ee262f2632c1d6",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":250,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4f65ffa30fc640b6ac55ef614d06c88f",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":250,
                          "y":0},
                        "size":{
                          "width":125,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open setting in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"setting.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u8.png"}}]}]},
{
          "id":"82c68b868bf243dcab8e944220f0f81a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":411,
              "y":360},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e3f17269fc840cfa092eccd1d1dee72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":411,
                  "y":360},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d0514a3d76674fc2abc45894aa522019":{
      "scriptId":"u0"},
    "ad02e4e277724cf5a5dd96bc7aed422b":{
      "scriptId":"u1"},
    "01d8a89949864262af329337b1b05a65":{
      "scriptId":"u2"},
    "3ac1b31e714e41688e7b28a3a29d8183":{
      "scriptId":"u3"},
    "49746ca9e13f48e8a173c2051a01522f":{
      "scriptId":"u4"},
    "c4092257f08843caac08804c007121e5":{
      "scriptId":"u5"},
    "268790c6c5534d1f9965b945a5983b58":{
      "scriptId":"u6"},
    "07cb06d9d2be4e7490b42df68779b11b":{
      "scriptId":"u7"},
    "2c0162fe40c949e9a98ace9656e08eec":{
      "scriptId":"u8"},
    "ef1d9b194d8748edb22d224a26aa5af8":{
      "scriptId":"u9"},
    "2f881690fd15417983375c0d3b170beb":{
      "scriptId":"u10"},
    "3cfa170e8ef0498f8691ed28fb42c0c2":{
      "scriptId":"u11"},
    "2ab043dd0e9541be9c3fed467e4f817d":{
      "scriptId":"u12"},
    "133e382b03ac40e3a192438541fb8e97":{
      "scriptId":"u13"},
    "a2f973229a2c4bc7a22ec8f7f36d9eb7":{
      "scriptId":"u14"},
    "7f78bcaf1f9b4e2b820225cb61d9243d":{
      "scriptId":"u15"},
    "f49a1a804c204a3484ee262f2632c1d6":{
      "scriptId":"u16"},
    "4f65ffa30fc640b6ac55ef614d06c88f":{
      "scriptId":"u17"},
    "82c68b868bf243dcab8e944220f0f81a":{
      "scriptId":"u18"},
    "3e3f17269fc840cfa092eccd1d1dee72":{
      "scriptId":"u19"}}});