$axure.loadCurrentPage({
  "url":"volum.html",
  "generationDate":new Date(1444806060432.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3065fae4926f4495a723de5ec69a717c",
    "type":"Axure:Page",
    "name":"volum",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d0514a3d76674fc2abc45894aa522019",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":23},
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad02e4e277724cf5a5dd96bc7aed422b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":23},
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"2c1beeac599846eaad2201f758ed1fc1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":40},
            "size":{
              "width":360,
              "height":607}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"763a2939b8cd4e698b2c368b4bec9c62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":40},
                "size":{
                  "width":360,
                  "height":607}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/manage3/u2.png"}},
{
          "id":"88a81f866f144d88a572e0fd6f89f49d",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":660},
            "size":{
              "width":375,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7580ea5e1ac04e35b92a6616f51cf96b",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bd21aa9207824a9ca78bcf3d3f9adcd8",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":75,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f45e79b2461a497ea12ffc3cc99a6bd7",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":75,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/manage3/u6.png"}},
{
                  "id":"5563b853fa12497285392d0b3524c433",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":75,
                      "y":0},
                    "size":{
                      "width":75,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"df37934738b343ec84fe7f246c18a8e7",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":75,
                          "y":0},
                        "size":{
                          "width":75,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open video in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"video.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/manage3/u6.png"}},
{
                  "id":"6ae3479f5b684233b177329d3cf0ed70",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":150,
                      "y":0},
                    "size":{
                      "width":75,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9336173503dc47afb99bd24aad97afa0",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":150,
                          "y":0},
                        "size":{
                          "width":75,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open invite in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"invite.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/manage3/u6.png"}},
{
                  "id":"360fd8791e4846519ea8d2ed61a05eed",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":225,
                      "y":0},
                    "size":{
                      "width":75,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3bdb817edfe54b62b169cc48a0181efe",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":225,
                          "y":0},
                        "size":{
                          "width":75,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open member in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"member.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/manage3/u6.png"}},
{
                  "id":"6ec8fd49099e4fe7bfcc49220655b053",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":75,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5fbab44931304655827a8bc84a8f3eea",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":75,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open more in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"more.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/manage3/u14.png"}}]}]},
{
          "id":"37059d93c34642a18b55a5da4fa464aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":630},
            "size":{
              "width":75,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4714ba56f11142dabec193b41c7756ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":630},
                "size":{
                  "width":75,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/volum/u16.png"}},
{
          "id":"608a86aefa744df3987a95a752e534a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":600},
            "size":{
              "width":75,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2c68862c2924e9c91f44e6a411316a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":600},
                "size":{
                  "width":75,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/volum/u16.png"}},
{
          "id":"0d13b7908e7a45558928f6326017c092",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":55},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e512dcd4fb944e84a393979f87d71089",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":55},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "d0514a3d76674fc2abc45894aa522019":{
      "scriptId":"u0"},
    "ad02e4e277724cf5a5dd96bc7aed422b":{
      "scriptId":"u1"},
    "2c1beeac599846eaad2201f758ed1fc1":{
      "scriptId":"u2"},
    "763a2939b8cd4e698b2c368b4bec9c62":{
      "scriptId":"u3"},
    "88a81f866f144d88a572e0fd6f89f49d":{
      "scriptId":"u4"},
    "7580ea5e1ac04e35b92a6616f51cf96b":{
      "scriptId":"u5"},
    "bd21aa9207824a9ca78bcf3d3f9adcd8":{
      "scriptId":"u6"},
    "f45e79b2461a497ea12ffc3cc99a6bd7":{
      "scriptId":"u7"},
    "5563b853fa12497285392d0b3524c433":{
      "scriptId":"u8"},
    "df37934738b343ec84fe7f246c18a8e7":{
      "scriptId":"u9"},
    "6ae3479f5b684233b177329d3cf0ed70":{
      "scriptId":"u10"},
    "9336173503dc47afb99bd24aad97afa0":{
      "scriptId":"u11"},
    "360fd8791e4846519ea8d2ed61a05eed":{
      "scriptId":"u12"},
    "3bdb817edfe54b62b169cc48a0181efe":{
      "scriptId":"u13"},
    "6ec8fd49099e4fe7bfcc49220655b053":{
      "scriptId":"u14"},
    "5fbab44931304655827a8bc84a8f3eea":{
      "scriptId":"u15"},
    "37059d93c34642a18b55a5da4fa464aa":{
      "scriptId":"u16"},
    "4714ba56f11142dabec193b41c7756ce":{
      "scriptId":"u17"},
    "608a86aefa744df3987a95a752e534a6":{
      "scriptId":"u18"},
    "c2c68862c2924e9c91f44e6a411316a2":{
      "scriptId":"u19"},
    "0d13b7908e7a45558928f6326017c092":{
      "scriptId":"u20"},
    "e512dcd4fb944e84a393979f87d71089":{
      "scriptId":"u21"}}});