$axure.loadCurrentPage({
  "url":"manage.html",
  "generationDate":new Date(1444806060976.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7c649d0d71bb4c28968489e2c1fb881e",
    "type":"Axure:Page",
    "name":"manage",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8fabb4a87e954c29a3457aaaa485f6a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":143},
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"351b49985a2d48e68d94b11cf9ca070b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":287,
                  "y":143},
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"c5bac97aee4a4491beecd5709acad012",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":307,
              "y":160},
            "size":{
              "width":340,
              "height":610}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc3e9a7f01184013b86a67f089f507d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":307,
                  "y":160},
                "size":{
                  "width":340,
                  "height":610}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/logined/u2.png"}},
{
          "id":"e1713ec7298b4b1fad23133670533655",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":184},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5042cf6e218b42d28fd19ef28e1b2dc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":184},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd80a2c71918445b84246c2e1fdc8721",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":407,
              "y":180},
            "size":{
              "width":130,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f2bc850f64e54de384033bb7d80c0f1e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":557,
              "y":180},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"409952b8378c42aaa5cdd0515d80d2c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":325,
              "y":376},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00f7e0b8fc3742c8a0d1cc68a156305d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":325,
                  "y":376},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"812f0c6007e5415bb06e0d1ae1208d61",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":402},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3cd4a10972a472e9bc71b79d714d21e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":387,
                  "y":402},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open manage1 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"manage1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59048bd4b07447cba2fcff03fbc4d3b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":399,
              "y":380},
            "size":{
              "width":10,
              "height":10},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36eb3b44dfbb42f6b4ddccebdecd529e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":399,
                  "y":380},
                "size":{
                  "width":10,
                  "height":10},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/logined/u14.png"}},
{
          "id":"9d082a8feba246c08d91c5ed01992378",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":428},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32e2b6fbee144a71a24f9b5d5da335b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":387,
                  "y":428},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open manage1 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"manage1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3950ede12bc43998e496a0b3ee3a0b4",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":779},
            "size":{
              "width":375,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4715f3225ada42168b6e94b6ad36d51f",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"75b84c44e6714c9cab3ed5a47eb7e395",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5471901520404f5fac35214d4a6bd204",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":125,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open manage in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"manage.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u4.png"}},
{
                  "id":"2c7bd04157224d8c901d1f9f8f1042e7",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":125,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cca96b0af1904e1e832aab6de2aa0565",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":125,
                          "y":0},
                        "size":{
                          "width":125,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open manage2 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"manage2.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u4.png"}},
{
                  "id":"d6bab04b67cc4bf4909f203022eddf48",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":250,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ceafec9ac8f540b0a60fa684bc66818e",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":250,
                          "y":0},
                        "size":{
                          "width":125,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open setting in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"setting.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u8.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "8fabb4a87e954c29a3457aaaa485f6a7":{
      "scriptId":"u0"},
    "351b49985a2d48e68d94b11cf9ca070b":{
      "scriptId":"u1"},
    "c5bac97aee4a4491beecd5709acad012":{
      "scriptId":"u2"},
    "cc3e9a7f01184013b86a67f089f507d3":{
      "scriptId":"u3"},
    "e1713ec7298b4b1fad23133670533655":{
      "scriptId":"u4"},
    "5042cf6e218b42d28fd19ef28e1b2dc3":{
      "scriptId":"u5"},
    "fd80a2c71918445b84246c2e1fdc8721":{
      "scriptId":"u6"},
    "f2bc850f64e54de384033bb7d80c0f1e":{
      "scriptId":"u7"},
    "409952b8378c42aaa5cdd0515d80d2c8":{
      "scriptId":"u8"},
    "00f7e0b8fc3742c8a0d1cc68a156305d":{
      "scriptId":"u9"},
    "812f0c6007e5415bb06e0d1ae1208d61":{
      "scriptId":"u10"},
    "a3cd4a10972a472e9bc71b79d714d21e":{
      "scriptId":"u11"},
    "59048bd4b07447cba2fcff03fbc4d3b0":{
      "scriptId":"u12"},
    "36eb3b44dfbb42f6b4ddccebdecd529e":{
      "scriptId":"u13"},
    "9d082a8feba246c08d91c5ed01992378":{
      "scriptId":"u14"},
    "32e2b6fbee144a71a24f9b5d5da335b8":{
      "scriptId":"u15"},
    "c3950ede12bc43998e496a0b3ee3a0b4":{
      "scriptId":"u16"},
    "4715f3225ada42168b6e94b6ad36d51f":{
      "scriptId":"u17"},
    "75b84c44e6714c9cab3ed5a47eb7e395":{
      "scriptId":"u18"},
    "5471901520404f5fac35214d4a6bd204":{
      "scriptId":"u19"},
    "2c7bd04157224d8c901d1f9f8f1042e7":{
      "scriptId":"u20"},
    "cca96b0af1904e1e832aab6de2aa0565":{
      "scriptId":"u21"},
    "d6bab04b67cc4bf4909f203022eddf48":{
      "scriptId":"u22"},
    "ceafec9ac8f540b0a60fa684bc66818e":{
      "scriptId":"u23"}}});