$axure.loadCurrentPage({
  "url":"logined.html",
  "generationDate":new Date(1444806060080.84),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f29ab07c355a4643b48be04c0213f746",
    "type":"Axure:Page",
    "name":"logined",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d0514a3d76674fc2abc45894aa522019",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":23},
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad02e4e277724cf5a5dd96bc7aed422b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":23},
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"6dc4361bf91947ceb1c51a4221a20bb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":40},
            "size":{
              "width":340,
              "height":610}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c71040036848451a96c5b63785deb0d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":40},
                "size":{
                  "width":340,
                  "height":610}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/logined/u2.png"}},
{
          "id":"347ed6a6af2245d3bfdc191ecb2c3984",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":248,
              "y":64},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd65613f9916479eadfe952eae633a21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":248,
                  "y":64},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74093de7df8c42fda3fd98dd5db38985",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":60},
            "size":{
              "width":130,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bcd5277dcd924ce6b052e5378155bd50",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":60},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e18248934ab048009abf219fdd35cce2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":248,
              "y":256},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e44f24c52e144f38ee8fb7b43799453",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":248,
                  "y":256},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d10ddbb4b524e64bc0207f8c916392e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":282},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7159b89f5482474d92baf61c491829ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":282},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open manage3 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"manage3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f430d3b0723d4856a14c6e1af29c6127",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":248,
              "y":338},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ed18c46eef746919d0ef7f99708281e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":248,
                  "y":338},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59467526c09f4fa58805f61948e2fd44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":260},
            "size":{
              "width":10,
              "height":10},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d513707c6f4461a885bec4a29bd2b22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":260},
                "size":{
                  "width":10,
                  "height":10},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/logined/u14.png"}},
{
          "id":"75c5754db3d045f0a28d629557754c1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":318,
              "y":341},
            "size":{
              "width":10,
              "height":10},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"868f0843ea0c4552955c9e10f52202b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":318,
                  "y":341},
                "size":{
                  "width":10,
                  "height":10},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/logined/u14.png"}},
{
          "id":"3ac5f842ed6b489fabf49ebf89539b83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":308},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5ca34830c604a558eab4ea1f6d35c14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":308},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open manage3 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"manage3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ef9b460d3d545f982481a826a5b8062",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":382},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5fffe18897f4240bf6d81d43bbb1246",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":382},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open manage3 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"manage3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b74b2dcd975841c48568f0c5c8887771",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":408},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"537fee59e65845d9b78d24092a58e871",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":408},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open manage3 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"manage3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e5c955ed7dc47e08295878d1a4091b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":434},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfec0cf510a54669ae860534636cd48e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":434},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open manage3 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"manage3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bf7709053f24272afc530be4482d911",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":248,
              "y":460},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e10127a45491406e8dfa5c30bb7954dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":248,
                  "y":460},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b7698f68834435bbdca9a2ffb7d1d24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":318,
              "y":463},
            "size":{
              "width":10,
              "height":10},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"556af79a0878479ca99866b66993d3f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":318,
                  "y":463},
                "size":{
                  "width":10,
                  "height":10},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/logined/u14.png"}},
{
          "id":"70c0214959a44d20a129e0a0a28af279",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":318,
              "y":508},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6602de2a7e26460e87237ff9aef7e4ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":318,
                  "y":508},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open manage3 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"manage3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1275460d8c7647aab59a370d2a4b65ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":318,
              "y":534},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4ab1cda08574c189f6577b92414b7ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":318,
                  "y":534},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open manage3 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"manage3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51adec7588084d75a69f13ee9caae6ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":248,
              "y":142},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6698454226ba4b1699ab1ee9d51093f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":248,
                  "y":142},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"814d26be581d45609e567a4d9af544da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":168},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b383c26d22684c5aa83fc38157e52b47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":168},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open manage3 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"manage3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6940e90f368a476496e452cabeef43d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":146},
            "size":{
              "width":10,
              "height":10},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee4139d3d8a34a05ac9a0770eeb0f180",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":146},
                "size":{
                  "width":10,
                  "height":10},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/logined/u14.png"}},
{
          "id":"9fa2dd4721b349fa8cec3cb40f378593",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":194},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e87b46dfdf240758b61e07645eccf26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":194},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open manage3 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"manage3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5b28b35cb814f099b0db5f3b020a29d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":443,
              "y":168},
            "size":{
              "width":121,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c4df97ebe83447ea2840fb1e3ede0a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":443,
                  "y":168},
                "size":{
                  "width":121,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea83ba5216fe496181b3cb92884e7eb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":443,
              "y":194},
            "size":{
              "width":121,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b93fe19875d4030a8ff16217e273526",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":443,
                  "y":194},
                "size":{
                  "width":121,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"000aca6c750a420c861f2dd6e1380e63",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":659},
            "size":{
              "width":375,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"822faf535d4b4738adfaa5364040eded",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6a0518c1059646289a36b61c81ea6943",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"069c307179534e3eb36b656e821ec7dc",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":125,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Home in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"home.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u4.png"}},
{
                  "id":"cb77b594c67948179b82af6b48ed0456",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":125,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"efd8460b074d4c79bff0134fba851cc1",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":125,
                          "y":0},
                        "size":{
                          "width":125,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open manage in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"manage.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u4.png"}},
{
                  "id":"27e278bd70ae4e47ba1c20d01d4d7738",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":250,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e592f2f92c1d4b19bcc77bf9854ad969",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":250,
                          "y":0},
                        "size":{
                          "width":125,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open setting in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"setting.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u8.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "d0514a3d76674fc2abc45894aa522019":{
      "scriptId":"u0"},
    "ad02e4e277724cf5a5dd96bc7aed422b":{
      "scriptId":"u1"},
    "6dc4361bf91947ceb1c51a4221a20bb8":{
      "scriptId":"u2"},
    "c71040036848451a96c5b63785deb0d1":{
      "scriptId":"u3"},
    "347ed6a6af2245d3bfdc191ecb2c3984":{
      "scriptId":"u4"},
    "bd65613f9916479eadfe952eae633a21":{
      "scriptId":"u5"},
    "74093de7df8c42fda3fd98dd5db38985":{
      "scriptId":"u6"},
    "bcd5277dcd924ce6b052e5378155bd50":{
      "scriptId":"u7"},
    "e18248934ab048009abf219fdd35cce2":{
      "scriptId":"u8"},
    "4e44f24c52e144f38ee8fb7b43799453":{
      "scriptId":"u9"},
    "6d10ddbb4b524e64bc0207f8c916392e":{
      "scriptId":"u10"},
    "7159b89f5482474d92baf61c491829ea":{
      "scriptId":"u11"},
    "f430d3b0723d4856a14c6e1af29c6127":{
      "scriptId":"u12"},
    "9ed18c46eef746919d0ef7f99708281e":{
      "scriptId":"u13"},
    "59467526c09f4fa58805f61948e2fd44":{
      "scriptId":"u14"},
    "3d513707c6f4461a885bec4a29bd2b22":{
      "scriptId":"u15"},
    "75c5754db3d045f0a28d629557754c1d":{
      "scriptId":"u16"},
    "868f0843ea0c4552955c9e10f52202b7":{
      "scriptId":"u17"},
    "3ac5f842ed6b489fabf49ebf89539b83":{
      "scriptId":"u18"},
    "f5ca34830c604a558eab4ea1f6d35c14":{
      "scriptId":"u19"},
    "2ef9b460d3d545f982481a826a5b8062":{
      "scriptId":"u20"},
    "d5fffe18897f4240bf6d81d43bbb1246":{
      "scriptId":"u21"},
    "b74b2dcd975841c48568f0c5c8887771":{
      "scriptId":"u22"},
    "537fee59e65845d9b78d24092a58e871":{
      "scriptId":"u23"},
    "1e5c955ed7dc47e08295878d1a4091b9":{
      "scriptId":"u24"},
    "dfec0cf510a54669ae860534636cd48e":{
      "scriptId":"u25"},
    "5bf7709053f24272afc530be4482d911":{
      "scriptId":"u26"},
    "e10127a45491406e8dfa5c30bb7954dd":{
      "scriptId":"u27"},
    "9b7698f68834435bbdca9a2ffb7d1d24":{
      "scriptId":"u28"},
    "556af79a0878479ca99866b66993d3f1":{
      "scriptId":"u29"},
    "70c0214959a44d20a129e0a0a28af279":{
      "scriptId":"u30"},
    "6602de2a7e26460e87237ff9aef7e4ea":{
      "scriptId":"u31"},
    "1275460d8c7647aab59a370d2a4b65ed":{
      "scriptId":"u32"},
    "c4ab1cda08574c189f6577b92414b7ba":{
      "scriptId":"u33"},
    "51adec7588084d75a69f13ee9caae6ff":{
      "scriptId":"u34"},
    "6698454226ba4b1699ab1ee9d51093f1":{
      "scriptId":"u35"},
    "814d26be581d45609e567a4d9af544da":{
      "scriptId":"u36"},
    "b383c26d22684c5aa83fc38157e52b47":{
      "scriptId":"u37"},
    "6940e90f368a476496e452cabeef43d5":{
      "scriptId":"u38"},
    "ee4139d3d8a34a05ac9a0770eeb0f180":{
      "scriptId":"u39"},
    "9fa2dd4721b349fa8cec3cb40f378593":{
      "scriptId":"u40"},
    "1e87b46dfdf240758b61e07645eccf26":{
      "scriptId":"u41"},
    "c5b28b35cb814f099b0db5f3b020a29d":{
      "scriptId":"u42"},
    "1c4df97ebe83447ea2840fb1e3ede0a7":{
      "scriptId":"u43"},
    "ea83ba5216fe496181b3cb92884e7eb9":{
      "scriptId":"u44"},
    "3b93fe19875d4030a8ff16217e273526":{
      "scriptId":"u45"},
    "000aca6c750a420c861f2dd6e1380e63":{
      "scriptId":"u46"},
    "822faf535d4b4738adfaa5364040eded":{
      "scriptId":"u47"},
    "6a0518c1059646289a36b61c81ea6943":{
      "scriptId":"u48"},
    "069c307179534e3eb36b656e821ec7dc":{
      "scriptId":"u49"},
    "cb77b594c67948179b82af6b48ed0456":{
      "scriptId":"u50"},
    "efd8460b074d4c79bff0134fba851cc1":{
      "scriptId":"u51"},
    "27e278bd70ae4e47ba1c20d01d4d7738":{
      "scriptId":"u52"},
    "e592f2f92c1d4b19bcc77bf9854ad969":{
      "scriptId":"u53"}}});